import { INestApplication } from '@nestjs/common';
import { DataSource } from 'typeorm';
import request from 'supertest';

import { createCrudTestApp } from '../helper/testing-module';
import { seedTestData } from '../helper/seed-data';
import { User } from '../helper/entities/user-test.entity';

/**
 * End-to-end HTTP tests for the routes generated by `@Crud()`.
 * Exercises the real Nest request pipeline (param/query/body binding, the
 * RequestQueryParser, FindQueryBuilder and CrudService) over an in-memory DB.
 */
describe('CRUD HTTP routes', () => {
    let app: INestApplication;
    let dataSource: DataSource;

    beforeAll(async () => {
        app = await createCrudTestApp({
            entity: User,
            path: 'users',
            routes: {
                findMany: { enabled: true },
                findAll: { enabled: true },
                counts: { enabled: true },
                findOne: { enabled: true },
                create: { enabled: true },
                createMany: { enabled: true },
                update: { enabled: true },
                updateMany: { enabled: true },
                delete: { enabled: true },
                deleteMany: { enabled: true },
            },
        });
        dataSource = app.get(DataSource);
    });

    afterAll(async () => {
        await app.close();
    });

    // Fresh schema per test for isolation.
    beforeEach(async () => {
        await dataSource.synchronize(true);
    });

    const http = () => request(app.getHttpServer());

    describe('read routes (seeded)', () => {
        beforeEach(async () => {
            await seedTestData(dataSource, dataSource.getRepository(User));
        });

        it('GET / returns a { items, total } envelope', async () => {
            const res = await http().get('/users').expect(200);
            expect(Array.isArray(res.body.items)).toBe(true);
            expect(res.body.items).toHaveLength(2);
            expect(res.body.total).toBe(2);
        });

        it('GET / honours take/skip pagination', async () => {
            const res = await http().get('/users').query({ take: 1, skip: 1 }).expect(200);
            expect(res.body.items).toHaveLength(1);
            expect(res.body.total).toBe(2);
        });

        it('GET / filters via where', async () => {
            const res = await http()
                .get('/users')
                .query({ where: JSON.stringify({ status: { $eq: 'active' } }) })
                .expect(200);
            expect(res.body.items).toHaveLength(1);
            expect(res.body.items[0].status).toBe('active');
        });

        it('GET / sorts via order', async () => {
            const res = await http()
                .get('/users')
                .query({ order: JSON.stringify({ name: 'ASC' }) })
                .expect(200);
            const names = res.body.items.map((u: any) => u.name);
            expect(names).toEqual([...names].sort());
        });

        it('GET / loads relations', async () => {
            const res = await http()
                .get('/users')
                .query({ where: JSON.stringify({ name: { $eq: 'John Doe' } }), relations: JSON.stringify(['posts']) })
                .expect(200);
            expect(Array.isArray(res.body.items[0].posts)).toBe(true);
            expect(res.body.items[0].posts.length).toBeGreaterThan(0);
        });

        it('GET /get/all returns a bare array', async () => {
            const res = await http().get('/users/get/all').expect(200);
            expect(Array.isArray(res.body)).toBe(true);
            expect(res.body).toHaveLength(2);
        });

        it('GET /get/counts returns a total', async () => {
            const res = await http().get('/users/get/counts').expect(200);
            expect(res.body.total).toBe(2);
        });

        it('GET /get/counts groups by a key', async () => {
            const res = await http().get('/users/get/counts').query({ groupByKey: 'status' }).expect(200);
            expect(res.body.total).toBe(2);
            expect(Array.isArray(res.body.data)).toBe(true);
            const byStatus = Object.fromEntries(res.body.data.map((d: any) => [d.status, d.count]));
            expect(byStatus.active).toBe(1);
            expect(byStatus.inactive).toBe(1);
        });

        it('GET /:id returns a single record', async () => {
            const list = await http().get('/users').expect(200);
            const id = list.body.items[0].id;
            const res = await http().get(`/users/${id}`).expect(200);
            expect(res.body.id).toBe(id);
        });

        it('GET /:id returns 404 for a missing record', async () => {
            await http().get('/users/00000000-0000-0000-0000-000000000000').expect(404);
        });
    });

    describe('write routes', () => {
        const sample = { name: 'Alice', email: 'alice@example.com', status: 'active' };

        it('POST / creates a record (201)', async () => {
            const res = await http().post('/users').send(sample).expect(201);
            expect(res.body.id).toBeDefined();
            expect(res.body.name).toBe('Alice');
        });

        it('POST /bulk creates many records (201)', async () => {
            const res = await http()
                .post('/users/bulk')
                .send({ bulk: [sample, { name: 'Bob', email: 'bob@example.com', status: 'inactive' }] })
                .expect(201);
            expect(Array.isArray(res.body)).toBe(true);
            expect(res.body).toHaveLength(2);
            expect(res.body.every((u: any) => u.id)).toBe(true);
        });

        it('PUT /:id updates a record', async () => {
            const created = await http().post('/users').send(sample).expect(201);
            const res = await http().put(`/users/${created.body.id}`).send({ name: 'Alice 2' }).expect(200);
            expect(res.body.name).toBe('Alice 2');
        });

        it('PUT /bulk updates many records', async () => {
            const a = await http().post('/users').send(sample).expect(201);
            const b = await http().post('/users').send({ name: 'Bob', email: 'bob@example.com' }).expect(201);
            const res = await http()
                .put('/users/bulk')
                .send({ bulk: [{ id: a.body.id, name: 'A2' }, { id: b.body.id, name: 'B2' }] })
                .expect(200);
            expect(res.body).toHaveLength(2);
            const names = res.body.map((u: any) => u.name).sort();
            expect(names).toEqual(['A2', 'B2']);
        });

        it('DELETE /:id removes a record, then it 404s', async () => {
            const created = await http().post('/users').send(sample).expect(201);
            await http().delete(`/users/${created.body.id}`).expect(200);
            await http().get(`/users/${created.body.id}`).expect(404);
        });

        it('DELETE /delete/bulk removes many records by ids', async () => {
            const a = await http().post('/users').send(sample).expect(201);
            const b = await http().post('/users').send({ name: 'Bob' }).expect(201);
            await http().delete('/users/delete/bulk').query({ ids: [a.body.id, b.body.id] }).expect(200);
            const list = await http().get('/users').expect(200);
            expect(list.body.total).toBe(0);
        });
    });
});
