export const CRUD_OPTIONS_METADATA = 'NEST_CRUD_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'NEST_CRUD_CRUD_AUTH_OPTIONS_METADATA';
// export const CRUD_METHOD_NAME_KEY = 'nestCrudAction';
export const CRUD_ACTION_METADATA = 'NEST_CRUD_ACTION_METADATA';
